/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cmuguesser.UI;

/**
 *
 * @author user
 */
import java.awt.*;
import javax.swing.*;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private int x = -1;
    private int y = -1;
    private Image pin = new ImageIcon(getClass().getResource("/cmuguesser/Image/pin_1.png")
).getImage();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPage = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();
        home2 = new javax.swing.JPanel();
        standard = new javax.swing.JButton();
        Hardcore = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        game = new javax.swing.JPanel();
        map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMUGuesser");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        MainPage.setMaximumSize(new java.awt.Dimension(1920, 1080));
        MainPage.setMinimumSize(new java.awt.Dimension(1920, 1080));
        MainPage.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MainPage.setLayout(new java.awt.CardLayout());

        home.setMaximumSize(new java.awt.Dimension(1920, 1080));
        home.setMinimumSize(new java.awt.Dimension(1920, 1080));
        home.setPreferredSize(new java.awt.Dimension(1920, 1080));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmuguesser/Image/logo.png"))); // NOI18N
        home.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name :");
        home.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 740, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        home.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 740, 660, 80));

        start.setBackground(new java.awt.Color(137, 101, 229));
        start.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start");
        start.addActionListener(this::startActionPerformed);
        home.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 740, 230, 80));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmuguesser/Image/bg1.png"))); // NOI18N
        home.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPage.add(home, "home");

        home2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        home2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        home2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        home2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        standard.setBackground(new java.awt.Color(255, 255, 255));
        standard.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        standard.setForeground(new java.awt.Color(137, 101, 229));
        standard.setText("Standard");
        standard.addActionListener(this::standardActionPerformed);
        home2.add(standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 430, 260));

        Hardcore.setBackground(new java.awt.Color(255, 255, 255));
        Hardcore.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Hardcore.setForeground(new java.awt.Color(137, 101, 229));
        Hardcore.setText("Hardcore");
        Hardcore.addActionListener(this::HardcoreActionPerformed);
        home2.add(Hardcore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 530, 430, 260));

        bg2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmuguesser/Image/mode.png"))); // NOI18N
        home2.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPage.add(home2, "home2");

        game.setMaximumSize(new java.awt.Dimension(1920, 1080));
        game.setPreferredSize(new java.awt.Dimension(1920, 1080));

        map = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                if (x != -1 && y != -1) {
                    g.drawImage(pin, x - 20, y - 20, 40, 40, this);
                }
            }
        };
        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmuguesser/Image/map.png"))); // NOI18N
        map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gameLayout = new javax.swing.GroupLayout(game);
        game.setLayout(gameLayout);
        gameLayout.setHorizontalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLayout.createSequentialGroup()
                .addGap(0, 1307, Short.MAX_VALUE)
                .addComponent(map))
        );
        gameLayout.setVerticalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLayout.createSequentialGroup()
                .addGap(0, 311, Short.MAX_VALUE)
                .addComponent(map))
        );

        MainPage.add(game, "game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        CardLayout cl = (CardLayout) MainPage.getLayout();
        cl.show(MainPage, "home2");
    }//GEN-LAST:event_startActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        CardLayout cl = (CardLayout) MainPage.getLayout();
        cl.show(MainPage, "game");
    }//GEN-LAST:event_standardActionPerformed

    private void HardcoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardcoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HardcoreActionPerformed

    private void mapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapMouseClicked
        x = evt.getX();
        y = evt.getY();
        
        System.out.println(x + " " + y);
        map.repaint();
    }//GEN-LAST:event_mapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hardcore;
    private javax.swing.JPanel MainPage;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JPanel game;
    private javax.swing.JPanel home;
    private javax.swing.JPanel home2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel map;
    private javax.swing.JLabel name;
    private javax.swing.JButton standard;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
